#! /bin/bash
#! /usr/bin/env bash

data_dir=$HOME/.shortcuts
# data_dir=$HOME/code/termux-scripts/

radarr_key=$(cat $data_dir/secrets/radarr-api-key.txt)

response=$(curl --cacert <(echo quit | openssl s_client -showcerts -servername server -connect radarr.homelab.io:443) \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "X-Api-Key: ${radarr_key}" \
    -X POST 'https://radarr.homelab.io/api/v3/importlist' \
    -d '{
      "enabled": true,
      "enableAuto": true,
      "monitor": "movieOnly",
      "rootFolderPath": "/srv/media/movies",
      "qualityProfileId": 1,
      "searchOnAdd": true,
      "minimumAvailability": "released",
      "listType": "advanced",
      "listOrder": 6,
      "minRefreshInterval": "12:00:00",
      "name": "Letterboxd Radarr",
      "fields": [
        {
          "order": 0,
          "name": "url",
          "label": "List URL",
          "helpText": "The URL for the movie list",
          "value": "https://letterboxd-list-radarr.onrender.com/aitvann/list/radarr/",
          "type": "textbox",
          "advanced": false,
          "privacy": "normal",
          "isFloat": false
        }
      ],
      "implementationName": "Custom Lists",
      "implementation": "RadarrListImport",
      "configContract": "RadarrListSettings",
      "infoLink": "https://wiki.servarr.com/radarr/supported#radarrlistimport",
      "tags": []
    }')

echo "Create Import List Response: ${response}"

id=$(echo $response | jq .id)

echo "Import List Id: ${id}"

echo "Sleeping For 10s Waiting For Download To Start..."

sleep 10

curl --cacert <(echo quit | openssl s_client -showcerts -servername server -connect radarr.homelab.io:443) \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "X-Api-Key: ${radarr_key}" \
    -X DELETE "https://radarr.homelab.io/api/v3/importlist/{${id}}"
